import { chromium } from "playwright";
const dir = process.argv[2];
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1600, height: 1000 } })).newPage();
const errors = [];
page.on("console", m => { if (m.type() === "error") errors.push(m.text().slice(0, 140)); });
await page.goto("http://localhost:3001/dev", { waitUntil: "networkidle", timeout: 120000 });
await page.getByText("Just created (onboarding finished)").first().click();
await page.getByRole("button", { name: "Reset Just created" }).click(); await page.waitForTimeout(1200);
await page.getByText("Settings preview").first().click(); await page.waitForTimeout(2500);
const frame = page.frames().find(f => f.url().includes("/dev/tournament/settings"));
await frame.getByRole("button", { name: "Organizer", exact: true }).click();
await frame.getByRole("button", { name: "Competition", exact: true }).first().click();
await frame.getByRole("button", { name: "TEAM", exact: true }).click();
await frame.getByRole("button", { name: "2 Teams", exact: true }).click();
await frame.getByLabel("Team A name").fill("Sharks"); await frame.getByLabel("Team B name").fill("Jets");
// Put the organizer on Sharks and one open spot on Jets.
await frame.getByRole("button", { name: "Add Player" }).first().click();
await frame.getByRole("button", { name: "Jordan Lee", exact: true }).click();
await frame.getByRole("button", { name: /Add to Sharks/ }).click(); await page.waitForTimeout(300);
await frame.getByRole("button", { name: "Add Player" }).last().click();
await frame.getByRole("button", { name: "Player 2", exact: true }).click();
await frame.getByRole("button", { name: /Add to Jets/ }).click(); await page.waitForTimeout(300);
await frame.getByRole("button", { name: "Back to organizer settings" }).click();
await frame.getByRole("button", { name: "Golf Schedule" }).click(); await page.waitForTimeout(400);
await frame.getByRole("button", { name: /Round 1 .*Round settings/ }).click(); await page.waitForTimeout(500);
console.log("round page:", (await frame.locator("main").innerText()).split("\n").filter(Boolean).slice(0, 20).join(" | "));
await frame.getByRole("button", { name: /Match 1, Sharks: add player/ }).click(); await page.waitForTimeout(300);
await frame.getByRole("dialog", { name: /Match 1 Sharks player/ }).getByRole("button", { name: /Jordan Lee/ }).click(); await page.waitForTimeout(300);
await frame.getByRole("button", { name: /Match 1, Jets: add player/ }).click(); await page.waitForTimeout(300);
await frame.getByRole("dialog", { name: /Match 1 Jets player/ }).getByRole("button", { name: /Player 2/ }).click(); await page.waitForTimeout(300);
await page.screenshot({ path: dir + "/matches.png" });
console.log("match 1:", await frame.getByLabel("Match 1", { exact: true }).innerText().then(t => t.replace(/\n/g, " | ")));
console.log("errors:", JSON.stringify(errors.slice(0, 3)));
await page.getByRole("button", { name: "Reset Just created" }).click();
await browser.close();
