"use client";
import { useMemo, useState } from "react";
import { getPlayerDisplayName } from "@/lib/data/players";
import type { CareerHoleRecord } from "@/lib/data/careerStats";

const field = "w-full rounded-lg border-2 border-gold-300 bg-white px-3 py-2 font-sans text-sm text-ink-900";
const american = (p: number) => Math.round(p >= .5 ? -100 * p / (1-p) : 100 * (1-p) / p);
const odds = (p: number) => { const n=american(p); return n>0?`+${n}`:`${n}`; };

/** MM-MATCH-1.0. Samples completed 18-hole Career Stats score distributions.
 * Prefers the selected format and remaining-hole number; falls back only to
 * that same player's completed archive. Current score sets the match state. */
export function MatchSimulator({ records }: { records: CareerHoleRecord[] }) {
 const players=useMemo(()=>[...new Set(records.map(r=>r.player))].sort((a,b)=>getPlayerDisplayName(a).localeCompare(getPlayerDisplayName(b))),[records]);
 const [a,setA]=useState(players[0]??""); const [b,setB]=useState(players[1]??""); const [format,setFormat]=useState("Singles"); const [course,setCourse]=useState("All courses"); const [live,setLive]=useState(false); const [leader,setLeader]=useState("a"); const [up,setUp]=useState("1"); const [thru,setThru]=useState("0"); const [result,setResult]=useState<{a:number;tie:number;b:number}|null>(null);
 const courses=useMemo(()=>[...new Set(records.map(r=>r.course))].sort(),[records]);
 const reset=(change:()=>void)=>{change();setLive(false);setLeader("a");setUp("1");setThru("0");setResult(null)};
 const draw=(player:string,hole:number)=>{const base=records.filter(r=>r.player===player&&r.roundHoles===18&&r.format===format&&(course==="All courses"||r.course===course));const exact=base.filter(r=>r.hole===hole);const pool=exact.length>=3?exact:base.length?base:records.filter(r=>r.player===player&&r.roundHoles===18);return pool[Math.floor(Math.random()*pool.length)]?.score??4};
 const run=()=>{if(!a||!b||a===b)return;let aw=0,bw=0,tie=0;const start=Math.max(0,Math.min(17,+thru||0)),margin=Math.max(0,+up||0);for(let i=0;i<10000;i++){let lead=live?(leader==="a"?margin:-margin):0;for(let h=start+1;h<=18;h++){const x=draw(a,h),y=draw(b,h);if(x<y)lead++;if(y<x)lead--;if(Math.abs(lead)>18-h)break}if(lead>0)aw++;else if(lead<0)bw++;else tie++}setResult({a:aw/10000,b:bw/10000,tie:tie/10000})};
 return <section className="rounded-lg border-2 border-maroon-700 bg-cream-50 p-5"><p className="font-condensed text-2xs font-semibold uppercase tracking-wide text-maroon-700">MM-MATCH-1.0 · 10,000 simulations · fair American odds</p><h2 className="mt-1 font-serif text-xl font-bold">Match Simulator</h2><p className="mt-1 font-sans text-sm text-ink-600">Only completed Career Stats are sampled. Changing a player, format, or course resets to pre-round.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label>Format<select className={field} value={format} onChange={e=>reset(()=>setFormat(e.target.value))}><option>Singles</option><option>Fourball</option><option>Foursome</option></select></label><label>Course<select className={field} value={course} onChange={e=>reset(()=>setCourse(e.target.value))}><option>All courses</option>{courses.map(x=><option key={x}>{x}</option>)}</select></label><label>Player A<select className={field} value={a} onChange={e=>reset(()=>setA(e.target.value))}>{players.map(x=><option key={x} value={x}>{getPlayerDisplayName(x)}</option>)}</select></label><label>Player B<select className={field} value={b} onChange={e=>reset(()=>setB(e.target.value))}>{players.map(x=><option key={x} value={x}>{getPlayerDisplayName(x)}</option>)}</select></label></div><div className="mt-4 flex flex-wrap gap-3"><label>State<select className={field} value={live?"live":"pre"} onChange={e=>{setLive(e.target.value==="live");setResult(null)}}><option value="pre">Pre-round</option><option value="live">Live</option></select></label>{live&&<><label>Leader<select className={field} value={leader} onChange={e=>{setLeader(e.target.value);setResult(null)}}><option value="a">{getPlayerDisplayName(a)}</option><option value="b">{getPlayerDisplayName(b)}</option></select></label><label>Up<input className={field} type="number" min="1" value={up} onChange={e=>{setUp(e.target.value);setResult(null)}}/></label><label>Through<input className={field} type="number" min="0" max="17" value={thru} onChange={e=>{setThru(e.target.value);setResult(null)}}/></label></>}<button type="button" className="self-end rounded-lg bg-maroon-700 px-5 py-2 font-condensed text-sm font-semibold uppercase text-white" onClick={run}>Run Match Simulation</button></div>{result&&<table className="mt-5 w-full border border-gold-200 bg-white text-left font-sans text-sm"><thead><tr><th className="p-3">Outcome</th><th>Probability</th><th>Fair odds</th></tr></thead><tbody>{[[`${getPlayerDisplayName(a)} wins`,result.a],["Match halved",result.tie],[`${getPlayerDisplayName(b)} wins`,result.b]].map(([name,p])=><tr key={String(name)} className="border-t border-gold-100"><td className="p-3">{name}</td><td>{((p as number)*100).toFixed(1)}%</td><td className="font-bold text-maroon-700">{odds(p as number)}</td></tr>)}</tbody></table>}</section>
}
