"use client";

import { useEffect, useMemo, useState } from "react";
import { CategoryPills } from "@/components/stats/CategoryPills";
import { ComparePicker } from "@/components/stats/ComparePicker";
import { getPlayerDisplayName } from "@/lib/data/players";

type Row = { player: string; year: number; holes: number; strokes: number; birdies: number; bogeysPlus: number; fairwayHits: number; fairwayTotal: number; greenHits: number; greenTotal: number; putts: number; puttHoles: number };
type Key = "scoring" | "birdies" | "bogeys" | "fir" | "gir" | "putts";
const categories: { key: Key; label: string }[] = [{ key: "scoring", label: "Scoring Avg." }, { key: "birdies", label: "Birdies" }, { key: "bogeys", label: "Bogeys +" }, { key: "fir", label: "Fairways %" }, { key: "gir", label: "Greens %" }, { key: "putts", label: "Putts / Hole" }];
function combine(rows: Row[]) { return rows.reduce<Row>((sum, row) => ({ ...sum, holes: sum.holes + row.holes, strokes: sum.strokes + row.strokes, birdies: sum.birdies + row.birdies, bogeysPlus: sum.bogeysPlus + row.bogeysPlus, fairwayHits: sum.fairwayHits + row.fairwayHits, fairwayTotal: sum.fairwayTotal + row.fairwayTotal, greenHits: sum.greenHits + row.greenHits, greenTotal: sum.greenTotal + row.greenTotal, putts: sum.putts + row.putts, puttHoles: sum.puttHoles + row.puttHoles }), { player: "", year: 0, holes: 0, strokes: 0, birdies: 0, bogeysPlus: 0, fairwayHits: 0, fairwayTotal: 0, greenHits: 0, greenTotal: 0, putts: 0, puttHoles: 0 }); }
function value(row: Row, key: Key) { if (!row.holes) return 0; if (key === "scoring") return row.strokes / row.holes; if (key === "birdies") return row.birdies; if (key === "bogeys") return row.bogeysPlus; if (key === "fir") return row.fairwayTotal ? row.fairwayHits / row.fairwayTotal * 100 : 0; if (key === "gir") return row.greenTotal ? row.greenHits / row.greenTotal * 100 : 0; return row.puttHoles ? row.putts / row.puttHoles : 0; }
export function CareerArchiveStats({ playerSlug }: { playerSlug: string }) {
  const [rows, setRows] = useState<Row[]>([]), [year, setYear] = useState("career"), [compare, setCompare] = useState(""), [category, setCategory] = useState<Key>("scoring");
  useEffect(() => { fetch("/api/player-archive-stats", { cache: "no-store" }).then((res) => res.json()).then((data) => data.ok && setRows(data.rows)).catch(() => undefined); }, []);
  const years = useMemo(() => [...new Set(rows.map((row) => row.year))].sort((a, b) => b - a), [rows]);
  const players = useMemo(() => [...new Set(rows.map((row) => row.player))].filter((player) => player !== playerSlug).sort((a, b) => getPlayerDisplayName(a).localeCompare(getPlayerDisplayName(b))), [rows, playerSlug]);
  useEffect(() => { if (!compare && players.length) setCompare(players[0]); }, [compare, players]);
  const filtered = (player: string) => combine(rows.filter((row) => row.player === player && (year === "career" || row.year === Number(year))));
  const player = filtered(playerSlug), opponent = filtered(compare);
  if (!rows.length) return null;
  const playerValue = value(player, category), opponentValue = value(opponent, category), max = Math.max(playerValue, opponentValue, 1);
  const suffix = category === "fir" || category === "gir" ? "%" : category === "scoring" || category === "putts" ? "" : "";
  const format = (number: number) => (category === "fir" || category === "gir" ? Math.round(number) : category === "scoring" || category === "putts" ? number.toFixed(2) : String(Math.round(number))) + suffix;
  return <section className="mt-8"><h2 className="m-0 font-serif text-2xl font-bold text-maroon-700">Career Stats</h2><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-1"><button type="button" onClick={() => setYear("career")} className={year === "career" ? "rounded-pill bg-maroon-700 px-3 py-1.5 font-condensed text-xs font-bold text-white" : "rounded-pill bg-cream-100 px-3 py-1.5 font-condensed text-xs font-bold text-ink-600"}>Career</button>{years.map((item) => <button type="button" key={item} onClick={() => setYear(String(item))} className={year === String(item) ? "rounded-pill bg-maroon-700 px-3 py-1.5 font-condensed text-xs font-bold text-white" : "rounded-pill bg-cream-100 px-3 py-1.5 font-condensed text-xs font-bold text-ink-600"}>{item}</button>)}</div><ComparePicker players={players.map(getPlayerDisplayName)} value={getPlayerDisplayName(compare)} onChange={(name) => setCompare(players.find((player) => getPlayerDisplayName(player) === name) ?? "")} /></div><div className="mt-3"><CategoryPills categories={categories} selected={category} onSelect={setCategory} /></div><div className="mt-4 rounded-md border border-ink-100 bg-white p-4"><div className="space-y-5"><div><div className="mb-1 flex justify-between font-condensed text-xs font-bold uppercase tracking-wide text-maroon-700"><span>{getPlayerDisplayName(playerSlug)}</span><span>{format(playerValue)}</span></div><div className="h-7 rounded-sm bg-cream-100"><div className="h-full rounded-sm bg-maroon-700 transition-all" style={{ width: playerValue / max * 100 + "%" }} /></div></div><div><div className="mb-1 flex justify-between font-condensed text-xs font-bold uppercase tracking-wide text-ink-500"><span>{compare ? getPlayerDisplayName(compare) : "Comparison"}</span><span>{format(opponentValue)}</span></div><div className="h-7 rounded-sm bg-cream-100"><div className="h-full rounded-sm bg-ink-400 transition-all" style={{ width: opponentValue / max * 100 + "%" }} /></div></div></div><p className="mb-0 mt-4 font-sans text-xs text-ink-500">{year === "career" ? "Career totals from confirmed individual-ball archive holes." : "Confirmed individual-ball archive holes from " + year + "."} Alternate Shot remains a shared team archive and is not included in individual stroke statistics.</p></div></section>;
}
