import React from 'react';
import {createRoot} from 'react-dom/client';
import {LiveScoringPreview} from '../components/portal/tiger/LiveScoringPreview';
import {ScoringPreviewPhone} from '../components/portal/tiger/ScoringPreviewPhone';
const params=new URLSearchParams(location.search);
const format=params.get('format') as 'Singles'|'Fourball'|'Foursome' || 'Singles';
const matchBox={id:'preview',boxNumber:1,format,teeTime:'2026-01-03',maroonPlayers:format==='Singles'?['cam-latto']:['cam-latto','pete-peabody'],whitePlayers:format==='Singles'?['cade-barone']:['cade-barone','kyle-schnabel'],state:'Live'};
const pars=[4,4,5,3,4,5,3,4,4,4,3,4,4,4,5,4,3,5];
const state={matchBox,holes:pars.map((par,i)=>({number:i+1,par,yards:406})),scores:[],submittedPlayers:[]};
createRoot(document.getElementById('root')!).render(location.pathname.endsWith('/mobile')?<main className="px-4 pb-8"><ScoringPreviewPhone state={state} player={params.get('team')==='white'?'cade-barone':'cam-latto'} session={params.get('session')!}/></main>:<main className="mx-auto max-w-5xl p-4"><LiveScoringPreview/></main>);